"""
Ejemplos de Integración Git Automation con Atlas Agent
Uso avanzado de control de versiones automatizado
"""

import json

from tools_integration import tools


def demo_git_automation():
    """Demostración completa de capacidades Git automatizadas"""
    print("🔧 Atlas Git Automation - Integración Completa")
    print("=" * 50)

    # 1. Estado del repositorio
    print("\n1️⃣ Estado del Repositorio:")
    status = tools.git_get_status()
    print(f"   📁 Branch: {status.get('branch', 'N/A')}")
    print(f"   🧹 Limpio: {status.get('is_clean', 'N/A')}")
    print(f"   📝 Último commit: {status.get('last_commit', {}).get('hash', 'N/A')[:8]}")

    # 2. Crear archivo de prueba
    print("\n2️⃣ Creando archivo de prueba...")
    test_content = f"""
# Atlas Git Automation Test
Generated: {status.get('last_commit', {}).get('date', 'N/A')}
Branch: {status.get('branch', 'N/A')}
Files tracked: {len(status.get('modified_files', []))}
"""

    with open("git_test_file.md", "w") as f:
        f.write(test_content)

    # 3. Commit inteligente
    print("\n3️⃣ Commit Inteligente:")
    commit_result = tools.git_smart_commit(
        "feat(git): add automation test file\n\n- Generated by Atlas Git Automation\n- Tests smart commit functionality",
        files=["git_test_file.md"],
    )
    print(f"   ✅ Commit: {commit_result.get('ok', False)}")
    if commit_result.get("ok"):
        print(f"   📝 Hash: {commit_result.get('commit_hash', 'N/A')[:8]}")
        print(f"   📁 Archivos: {commit_result.get('files_changed', 0)}")

    # 4. Push automático
    print("\n4️⃣ Push Automático:")
    push_result = tools.git_smart_push()
    print(f"   ✅ Push: {push_result.get('ok', False)}")
    if push_result.get("ok"):
        print(f"   📤 Commits: {push_result.get('pushed_commits', 0)}")
        print(f"   🌐 Branch: {push_result.get('branch', 'N/A')}")

    # 5. Crear feature branch
    print("\n5️⃣ Crear Feature Branch:")
    feature_result = tools.git_create_branch("feature/git-automation-demo")
    print(f"   ✅ Branch: {feature_result.get('ok', False)}")
    if feature_result.get("ok"):
        print(f"   🌿 Nombre: {feature_result.get('branch', 'N/A')}")

    # 6. Workflow automatizado completo
    print("\n6️⃣ Workflow Automatizado:")
    workflow_result = tools.git_automated_workflow(
        "commit_and_push",
        message="feat(git): automated workflow test",
        files=["git_integration_examples.py"],
    )
    print(f"   ✅ Workflow: {workflow_result.get('ok', False)}")

    return {
        "status": status,
        "commit": commit_result,
        "push": push_result,
        "branch": feature_result,
        "workflow": workflow_result,
    }


def git_trading_workflow():
    """Workflow Git para trading automatizado"""
    print("\n💼 Git Workflow - Trading Automation")
    print("=" * 40)

    # 1. Analizar cambios de trading
    print("\n1️⃣ Analizando cambios de trading...")
    status = tools.git_get_status()

    trading_files = [
        f
        for f in status.get("modified_files", [])
        if any(keyword in f.lower() for keyword in ["trading", "atlas", "strategy"])
    ]

    if trading_files:
        print(f"   📊 Archivos de trading modificados: {len(trading_files)}")

        # 2. Commit de cambios de trading
        commit_result = tools.git_smart_commit(
            f"feat(trading): update strategy files\n\n- Modified: {', '.join(trading_files)}\n- Automated by Atlas Agent",
            files=trading_files,
        )

        # 3. Crear branch de estrategia
        strategy_branch = f"strategy/update-{datetime.now().strftime('%Y%m%d')}"
        branch_result = tools.git_create_branch(strategy_branch)

        # 4. Push de branch
        push_result = tools.git_smart_push(strategy_branch)

        print(f"   ✅ Trading workflow completado")
        return {
            "files": trading_files,
            "commit": commit_result,
            "branch": branch_result,
            "push": push_result,
        }
    else:
        print("   📋 No hay cambios de trading para commitear")
        return {"message": "No trading changes detected"}


def git_backup_workflow():
    """Workflow de backup automático"""
    print("\n💾 Git Workflow - Backup Automático")
    print("=" * 35)

    # 1. Estado actual
    status = tools.git_get_status()

    # 2. Crear tag de backup
    from datetime import datetime

    backup_tag = f"backup/{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    # 3. Commit de todos los cambios
    if not status.get("is_clean"):
        commit_result = tools.git_smart_commit(
            f"backup(automated): {backup_tag}\n\n- Auto-generated backup\n- All changes included",
            auto_stage=True,
        )

        # 4. Push a main
        push_result = tools.git_smart_push()

        print(f"   ✅ Backup completado: {backup_tag}")
        return {"tag": backup_tag, "commit": commit_result, "push": push_result}
    else:
        print("   📋 No hay cambios para backup")
        return {"message": "No changes for backup"}


def git_deployment_workflow():
    """Workflow de despliegue automatizado"""
    print("\n🚀 Git Workflow - Deployment Automation")
    print("=" * 45)

    # 1. Verificar branch actual
    status = tools.git_get_status()
    current_branch = status.get("branch", "main")

    # 2. Crear branch de deploy
    deploy_branch = f"deploy/{current_branch}-{datetime.now().strftime('%Y%m%d')}"
    branch_result = tools.git_create_branch(deploy_branch)

    # 3. Commit de cambios listos para deploy
    deploy_files = ["requirements.txt", "workspace_prime/", "config/"]
    commit_result = tools.git_smart_commit(
        f"deploy(prepare): {deploy_branch}\n\n- Ready for deployment\n- All dependencies updated",
        files=deploy_files,
    )

    # 4. Push de branch de deploy
    push_result = tools.git_smart_push(deploy_branch)

    print(f"   ✅ Deployment workflow completado")
    return {
        "deploy_branch": deploy_branch,
        "commit": commit_result,
        "push": push_result,
    }


def main():
    """Ejecutar todos los workflows Git"""
    print("🎯 ATLAS GIT AUTOMATION - Workflows Completos")
    print("Integración avanzada de control de versiones")
    print("=" * 60)

    # Demo básica
    demo_results = demo_git_automation()

    # Workflow de trading
    trading_results = git_trading_workflow()

    # Workflow de backup
    backup_results = git_backup_workflow()

    # Workflow de deployment
    deploy_results = git_deployment_workflow()

    # Resumen final
    print("\n📊 RESUMEN DE WORKFLOWS GIT")
    print("=" * 30)
    print(f"🔧 Demo básica: {demo_results['commit'].get('ok', False)}")
    print(f"💼 Trading workflow: {trading_results.get('commit', {}).get('ok', False)}")
    print(f"💾 Backup workflow: {backup_results.get('commit', {}).get('ok', False)}")
    print(f"🚀 Deployment workflow: {deploy_results.get('commit', {}).get('ok', False)}")

    # Estado final del repo
    final_status = tools.git_get_status()
    print(f"\n🎯 Estado Final:")
    print(f"   📁 Branch: {final_status.get('branch', 'N/A')}")
    print(f"   🧹 Limpio: {final_status.get('is_clean', 'N/A')}")
    print(
        f"   📝 Último commit: {final_status.get('last_commit', {}).get('hash', 'N/A')[:8]}"
    )

    print(f"\n✅ Todos los workflows Git ejecutados exitosamente!")
    print(f"🔧 Atlas Git Automation está completamente integrado")


if __name__ == "__main__":
    from datetime import datetime

    main()
