apiVersion: 1
datasources:
  - name: atlas-prometheus
    uid: atlas-prom
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: '5s'
