"""Script factory: generate PowerShell and Python scripts with good practices."""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Dict, Optional

from .validators import validate_script


def _allowed_base() -> str:
    base = os.getenv("ATLAS_SCRIPTS_BASE") or os.getenv("POLICY_ALLOWED_PATHS", "C:\\ATLAS_PUSH").split(",")[0].strip()
    return base.rstrip("\\/")


def _sanitize_filename(name: str) -> str:
    return re.sub(r"[^\w\-\.]", "_", name).strip("_") or "script"


def generate_powershell(purpose: str, options: Optional[Dict[str, Any]] = None) -> str:
    """Generate a PowerShell script with param, try/catch, and structured output."""
    options = options or {}
    comment = options.get("comment", purpose)[:200]
    return f"""# {comment}
# Generated by ATLAS Script Factory - run with: .\\script.ps1 -ParamName value
param(
    [Parameter(Mandatory=$false)][string]$ParamName = "default"
)
$ErrorActionPreference = "Stop"
try {{
    # TODO: implement - {purpose[:80]}
    $result = @{{ ok = $true; message = "Done" }}
    $result | ConvertTo-Json
    exit 0
}} catch {{
    Write-Error $_.Exception.Message
    @{{ ok = $false; error = $_.Exception.Message }} | ConvertTo-Json
    exit 1
}}
"""


def generate_python(purpose: str, options: Optional[Dict[str, Any]] = None) -> str:
    """Generate a Python script with docstring, try/except, and optional JSON output."""
    options = options or {}
    comment = options.get("comment", purpose)[:200]
    return f'''"""{comment}
Generated by ATLAS Script Factory. Run: python script.py
"""
import json
import sys

def main():
    try:
        # TODO: implement - {purpose[:80]}
        result = {{"ok": True, "message": "Done"}}
        print(json.dumps(result))
        return 0
    except Exception as e:
        print(json.dumps({{"ok": False, "error": str(e)}}), file=sys.stderr)
        return 1

if __name__ == "__main__":
    sys.exit(main())
'''


def generate_script(
    kind: str,
    purpose: str,
    options: Optional[Dict[str, Any]] = None,
    base_path: Optional[str] = None,
    fs_controller: Any = None,
) -> Dict[str, Any]:
    """
    Generate script and optionally write to allowed path.
    Returns {ok, path, preview, how_to_run, validated, error}.
    """
    options = options or {}
    kind = (kind or "powershell").lower().strip()
    purpose = (purpose or "utility").strip()
    if kind not in ("powershell", "python"):
        kind = "powershell"

    if kind == "powershell":
        content = generate_powershell(purpose, options)
        ext = ".ps1"
        how_to_run = "powershell -ExecutionPolicy Bypass -File <path>"
    else:
        content = generate_python(purpose, options)
        ext = ".py"
        how_to_run = "python <path>"

    valid, missing = validate_script(kind, content)
    preview = content[:2000] + ("..." if len(content) > 2000 else "")

    out = {"ok": True, "path": "", "preview": preview, "how_to_run": how_to_run, "validated": valid, "missing": missing, "error": None}

    write_path = options.get("output_path") or base_path
    if not write_path:
        subdir = options.get("subdir") or "scripts"
        base = _allowed_base()
        name = _sanitize_filename(options.get("filename") or f"script_{kind}{ext}")
        if not name.endswith(ext):
            name += ext
        write_path = str(Path(base) / subdir / name)

    if fs_controller and write_path:
        parent = str(Path(write_path).parent)
        dir_r = fs_controller.ensure_dir(parent)
        if dir_r.get("ok"):
            w = fs_controller.write_text(write_path, content)
            if w.get("ok"):
                out["path"] = write_path
                try:
                    from modules.humanoid.memory_engine import store_artifact, ensure_thread
                    ensure_thread(None, f"script:{kind}")
                    store_artifact(None, None, "script", write_path, purpose[:200])
                except Exception:
                    pass
            else:
                out["ok"] = False
                out["error"] = w.get("error")
        else:
            out["ok"] = False
            out["error"] = dir_r.get("error")
    else:
        out["path"] = write_path or "(not written - no fs_controller or path)"

    return out
