# smoke test script
# Generated by ATLAS Script Factory - run with: .\script.ps1 -ParamName value
param(
    [Parameter(Mandatory=$false)][string]$ParamName = "default"
)
$ErrorActionPreference = "Stop"
try {
    # TODO: implement - smoke test script
    $result = @{ ok = $true; message = "Done" }
    $result | ConvertTo-Json
    exit 0
} catch {
    Write-Error $_.Exception.Message
    @{ ok = $false; error = $_.Exception.Message } | ConvertTo-Json
    exit 1
}
