"""Base templates for FastAPI, Flutter, Node/PWA scaffolds."""
from __future__ import annotations

from typing import Dict, List

FASTAPI_MINIMAL = {
    "main.py": """\"\"\"FastAPI app - generated by ATLAS scaffolder.\"\"\"
from fastapi import FastAPI

app = FastAPI(title="{{name}}", version="0.1.0")

@app.get("/")
def root():
    return {"ok": True, "app": "{{name}}"}

@app.get("/health")
def health():
    return {"ok": True}
""",
    "requirements.txt": "fastapi>=0.100.0\nuvicorn>=0.22.0\n",
    ".gitignore": "__pycache__/\n.venv/\n.env\n*.pyc\n",
}

FLUTTER_MINIMAL = {
    "pubspec.yaml": """name: {{name}}
description: Flutter app - generated by ATLAS.
version: 0.1.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
""",
    "lib/main.dart": """// {{name}} - generated by ATLAS
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: '{{name}}', home: const Home());
  }
}

class Home extends StatelessWidget {
  const Home({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('{{name}}')),
      body: const Center(child: Text('Hello')),
    );
  }
}
""",
}

NODE_PWA_MINIMAL = {
    "package.json": """{
  "name": "{{name}}",
  "version": "0.1.0",
  "description": "PWA - generated by ATLAS",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \\"No tests yet\\""
  }
}
""",
    "index.js": """// {{name}} - generated by ATLAS
const http = require('http');
const port = process.env.PORT || 3000;
const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ ok: true, app: '{{name}}' }));
});
server.listen(port, () => console.log('Listening on', port));
""",
}

TEMPLATES: Dict[str, Dict[str, str]] = {
    "fastapi": FASTAPI_MINIMAL,
    "flutter": FLUTTER_MINIMAL,
    "node": NODE_PWA_MINIMAL,
    "pwa": NODE_PWA_MINIMAL,
}


def get_template(app_type: str) -> Dict[str, str]:
    t = app_type.lower().strip()
    return TEMPLATES.get(t, TEMPLATES["fastapi"])
